defaults:
  - _self_

model: "dynamics"

dim: 512
action_dim: 7
image_size: 64
patch_size: 4
temporal_patch_size: 1
num_blocks: 12
dim_head: 64
heads: 8
ff_mult: 4
max_seq_len: 4000
sample_temperature: 1.0
sample_num_frames: 15