defaults:
  - _self_


model: "tokenizer"


dim: 512
num_frames: 16
codebook_size: 1024
image_size: 64
patch_size: 4
temporal_patch_size: 1
num_blocks: 8
dim_head: 64
heads: 8
ff_mult: 4
vq_loss_weight: 1.0
recons_loss_weight: 1.0