defaults:
  - default
  - /tokenizer/tokenizer
  - /lam/lam
  - /dynamics/dynamics
  - /dataset/dataset
  - _self_

model: genie_redux
mode: train

train:
  batch_size: 3
  grad_accum: 4

dynamics:
  max_seq_len: 8000

tokenizer_fpath: ${config.train.save_root_dpath}/tokenizer/tokenizer/model-150000.pt

eval:
  model_fpath: ${config.train.save_root_dpath}/${config.model}/${config.train.wandb_name}/model-150000.pt
  eval_control: "yes"
