defaults:
  - default
  - /tokenizer/tokenizer
  - /dynamics/dynamics
  - /dataset/dataset
  - _self_

model: genie_redux_guided
mode: train

train:
  batch_size: 4
  grad_accum: 3

tokenizer_fpath: ${config.train.save_root_dpath}/tokenizer/tokenizer/model-150000.pt

eval:
  model_fpath: ${config.train.save_root_dpath}/${config.model}/${config.train.wandb_name}/model-150000.pt
  eval_control: "yes"

dataset:
  apply_argmax_to_actions: false
