defaults:
  - default
  - /tokenizer/tokenizer
  - /dynamics/dynamics
  - _self_

model: genie_redux_guided
mode: train

train:
  dataset_root_dpath: "data_generation/datasets"
  dataset_name: "coinrun_v2.0.0"
  wandb_name: "genie_redux_guided"
  batch_size: 4
  grad_accum: 3

tokenizer_fpath: ${config.train.save_root_dpath}/tokenizer/tokenizer/model-150000.pt

eval:
  dataset_root_dpath: ${config.train.dataset_root_dpath}
  dataset_name: ${config.train.dataset_name}
  model_fpath: ${config.train.save_root_dpath}/${config.model}/${config.train.wandb_name}/model-150000.pt
  eval_control: "yes"