defaults:
  - default
  - /tokenizer/tokenizer.yaml
  - _self_

model: tokenizer
mode: train

train:
  dataset_root_dpath: "data_generation/datasets"
  dataset_name: "coinrun_v2.0.0"
  wandb_name: "tokenizer"
  batch_size: 7
  grad_accum: 2